name: Generate Docs

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependencies
      run: |
        npm ci
    - name: Recompile and push docs
      run: |
        echo $GITHUB_REF
        echo $GITHUB_HEAD_REF
        echo $GITHUB_BASE_REF
        npm run docs 
        git config --global user.name "github action"
        git config --global user.email "53011962+16lim21@users.noreply.github.com"
        git commit -m "recompiling docs"
        git push origin $GITHUB_HEAD_REF
