name: NodeJS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
    - name: Lint code with eslint
      run: npx eslint --debug
    - name: Run Tests
      env:
        NODE_ENV: production
        MONGODB_URI: ${{secrets.MONGODB_URI}}
        PORT: ${{secrets.PORT}}
      run: |
        ls -al
        npm run test
        npx nyc report --reporter=text-lcov > coverage.lcov
    - name: Upload to codecov
      run: npx codecov
    - name: Recompile and push docs
      run: |
        npm run docs 
        git config --global user.name "github action"
        git config --global user.email "53011962+16lim21@users.noreply.github.com"
        git commit -m "recompiling docs"
        git push origin HEAD:js
