name: NodeJS CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
    - name: Lint code with eslint
      run: npx eslint --debug
    - name: Run Tests
      env:
        NODE_ENV: production
        MONGODB_URI: ${{secrets.MONGODB_URI}}
        PORT: ${{secrets.PORT}}
      run: |
        npm run start &
        sleep 10 &&
        npm run test &&
        npx nyc report --reporter=text-lcov > coverage.lcov
    - name: Upload to codecov
      run: npx codecov
  
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependencies
      run: |
        npm ci
    - name: Build docs
      run: npm run docs
    - name: Recompile and deploy docs to github pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: true
