name: NodeJS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm ci
        npm run postinstall
    - name: Lint code with eslint
      run: npx eslint --debug
    - name: Run Tests
      env:
        NODE_ENV: production
        MONGODB_URI: ${{secrets.MONGODB_URI}}
        PORT: ${{secrets.PORT}}
      run: |
        npm link ./client/node_modules/react
        npx nyc mocha --recursive --exit
        npx nyc report --reporter=text-lcov > coverage.lcov
    - name: Upload to codecov
      run: npx codecov
